project:
  type: website
  output-dir: docs

website:
  title: "Chase J. Sakitis"
  search: false

  navbar:
    left:
      - href: research.qmd
        text: Research

      - href: publications.qmd
        text: Publications

      - href: software.qmd
        text: Software
        
    right:
      - icon: envelope-check-fill
        href: mailto:cjsakitis@cmh.edu
        text: Email

      - icon: file-earmark-text-fill
        href: files/Sakitis_CV_v2.pdf
        target: _blank
        text: CV

      - icon: github
        href: https://github.com/CJSakitis
        target: _blank
        text: GitHub

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css

